version: "3"
services:
  api:
    container_name: node-setup-api-api
    restart: always
    build:
      context: .
      dockerfile: ./src/microservices/api/Dockerfile
    env_file:
      - .env
    links:
      - mongo
    volumes:
      - ${API_LOGS_PATH}:/srv/logs
    ports:
      - "${API_OUTPUT_PORT}:3000"

  mongo:
    container_name: node-setup-api-mongo
    image: aashreys/mongo-auth:latest
    restart: always
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=${MONGO_ROOT_USER}
      - MONGODB_ADMIN_PASS=${MONGO_ROOT_PASSWORD}
      - MONGODB_APPLICATION_DATABASE=${MONGO_DB}
      - MONGODB_APPLICATION_USER=${MONGO_USER}
      - MONGODB_APPLICATION_PASS=${MONGO_PASSWORD}
    ports:
      - "${MONGO_OUTPUT_PORT}:27017"
    logging:
      driver: none